「1-1. カウントアップできるようにする」の対応を完了しました。
k-shimada-esm/modernChallenge pull request #2
Opened 2022-07-24 23:35 UTC by k-shimada-esm

@hyamakawa @yanagi-m @MitsukiTanaka
「1-1. カウントアップできるようにする」の対応を完了しましたので、レビューをお願いします。
https://script.google.com/a/macros/esm.co.jp/s/AKfycbylSjNCkbFthAl5suiX_ZWxSrfDNHvNNVrY8kP983vA-z7RLxCAmaHRiwjAJp-oAUdTcA/exec
↓ハードコピー
![image](https://user-images.githubusercontent.com/67683070/180636694-cc733732-7fd4-4641-93cc-c496894514b9.png)

2022-07-25 11:40 UTC, hyamakawa requested changes
@k-shimada-esm 初回プルリクお疲れ様です！確認しました。コメントのご確認お願いします 🙏

2022-07-25 11:40 UTC, hyamakawa commented on webApplication/appsscript.json
> +}
最後の空行いれますかっ。

2022-07-25 11:40 UTC, hyamakawa commented on webApplication/counterMain.js
> +  let template = HtmlService.createTemplateFromFile('index');
オブジェクトで保有しているプロパティの値を変える分にはletで宣言する必要はありません。
constでの変数宣言をお願いしますっ。

2022-07-25 11:40 UTC, hyamakawa commented on webApplication/index.html
> +        if (counter >= 99999) {
課題とは違う部分になりますが、、、
気持ち的には99999までは表示して、その後にカウントアップボタンを押すと1になって欲しいですｗ

2022-07-25 11:40 UTC, hyamakawa commented on webApplication/index.html
> +        document.getElementById('counter').value = ('00000' + counter).slice(-5);
`('00000' + counter).slice(-5)`がbody内に2箇所出てくるので共通化したいですね。

引数を渡すと、`('00000' + counter).slice(-5)`の処理結果を返してくれる関数を作成して、それぞれで呼び出すこととかは可能ですか？<?=  >の中で自作の関数呼べるかが自信なくてコメントしてます。。

2022-07-26 11:57 UTC, k-shimada-esm commented on webApplication/appsscript.json
> +}
最終行に改行を入れました。

2022-07-26 11:57 UTC, k-shimada-esm commented on webApplication/counterMain.js
> +  let template = HtmlService.createTemplateFromFile('index');
const に変更しました。

2022-07-26 12:05 UTC, k-shimada-esm commented on webApplication/index.html
> +        document.getElementById('counter').value = ('00000' + counter).slice(-5);
以下のように関数化したのですが、エラー「ReferenceError: formatCounter is not defined（行 13）」が出てしまったので、この方法にしました。

    <input type='text' id='counter' value=<?= formatCounter(counter) ?> disabled>

        // カウンターＢＯＸの内容更新
        document.getElementById('counter').value = formatCounter(counter);

      function formatCounter(counter) {
        return ('00000' + counter).slice(-5);
      }

2022-07-26 12:08 UTC, k-shimada-esm commented on webApplication/index.html
> +        if (counter >= 99999) {
その仕様になっています。
表示されている内容が99999の時「1」を、以外は「+1」するようなコードです。

2022-07-26 12:11 UTC, k-shimada-esm commented
@hyamakawa @yanagi-m @MitsukiTanaka
山川さんレビュー指摘の取り込みを行ったので、再レビューをお願いします。

2022-07-26 13:14 UTC, hyamakawa commented on webApplication/index.html
> +        if (counter >= 99999) {
ほんとですね、失礼しました。

2022-07-26 13:17 UTC, hyamakawa commented on webApplication/index.html
> +        document.getElementById('counter').value = ('00000' + counter).slice(-5);
alue=<?= ... ?> の中でオリジナルメソッドを呼ぶことはできないってことなんですかね、御意です。

2022-07-26 13:18 UTC, hyamakawa commented
@k-shimada-esm lgtm ⚽️

2022-07-31 01:47 UTC, merged

2022-07-31 01:47 UTC, k-shimada-esm commented
LGTM いただきましたのでマージしました。