3-1.Vue.jsを導入して作り替える の対応完了
k-shimada-esm/modernChallenge pull request #7
Opened 2022-08-27 02:42 UTC by k-shimada-esm

@hyamakawa @yanagi-m @MitsukiTanaka
「3-1.Vue.jsを導入して作り替える」の対応を完了しましたので、レビューをお願いします。
https://script.google.com/a/macros/esm.co.jp/s/AKfycbzqevMY1RjTcu79De4JvIe70ZeZs0ZMT5L1Q2-QMGABHQyZ0AXx7uXQ3ASGUPObTGqFQg/exec
![image](https://user-images.githubusercontent.com/67683070/187011174-b892f2a6-cf0d-4094-a446-7d628cb4163b.png)

2022-08-29 08:00 UTC, hyamakawa requested changes
@k-shimada-esm 確認しました。コメントしたのでご確認・ご対応よろしくお願いいたします🙏

2022-08-29 08:00 UTC, hyamakawa commented on webApplication/index.html
> +      google.script.run.withSuccessHandler(initializeVue).getCounter();
できれば createdやmountedでgetCounterを実行する形にしていただけるとうれしいです。
三田村さんのところにもコメントしたのですが、withSuccessHandlerの中でthis使ってdata部の項目への設定処理を書いて、うまくいってなかった感じでしょうか。
もしそうであれば、それはthisが別のものを指していたからうまくいってなかったんだと思います。
thisはどこで実行するかによって指すものが変わるので、javascriptではちょとややこしいものになってます。
現時点の対応としては、withSuccessHandlerの中に直接設定処理を書かずに、一度関数を挟んで、その関数の中で設定処理を書く、というものになるのかなと思ってます。

伝わりましたでしょうか。。。

2022-09-03 04:05 UTC, k-shimada-esm commented
@hyamakawa 
mountedでgetCounterを実行する形に修正しましたので、ご確認をお願いします。

2022-09-03 06:37 UTC, k-shimada-esm commented on webApplication/index.html
> +      google.script.run.withSuccessHandler(initializeVue).getCounter();
> thisはどこで実行するかによって指すものが変わるので、javascriptではちょとややこしいものになってます。

試してみました。直書きのfunctionにした場合、「this.xxx」を使用すると何も起こらない。でも「app.xxx」とすると正常に動作しました。
いろいろ調べていたらアロー関数の「thisのスコープ」について書かれていました。
https://qiita.com/_Keitaro_/items/d48733a19c10889e2365
>アロー関数のthisは、functionの時のようにインスタンス内ではそのインスタンスを指すという動きはしません。なぜなら、アロー関数は呼び出された場所をthisとするという動きをするからです。

もしかしたらgoogle.script.run.withSuccessHandler(コールバック関数).GAS関数()って内部的にアロー関数のような動作をしているのかな。試しに以下を実行したら呼び元のcounterValueの値が変わりました。
　testCounter: function() {
　　let counterValue = -20;
　　google.script.run.withSuccessHandler(
　　　function (pData) {
　　　　let counterValue = -30;
　　　　this.counterValue = pData.counter;
　　　　console.log(counterValue);　　　　　　　　// → -30
　　　　console.log(this.counterValue);　　　　　　// → スプレッドシートの内容が表示
　　　　console.log(app.counterValue);　　　　　　// → 画面に表示されている内容が表示
　　　}
　　).getCounter();
          },

2022-09-04 23:58 UTC, hyamakawa approved these changes
lgtm 🐿

ですが、`upCounter ` `saveCounter ` `resetCounter ` `initializeData ` `itemDisplayFormat ` を下記の形式でも記載できますので、次回プルリク、もしくはこのプルリクで直してもいいのかなと思いました。mountedもどうように `mounted () {}` で記載できます。function って毎回書くの面倒ですよね、きっと。

``` javascript
methods: {
  xxx () {
  },
  yyy () {
  }
}
```

2022-09-05 12:38 UTC, k-shimada-esm commented
@hyamakawa 
vue関数定義を簡略化しました。ご確認をお願いします。。
https://script.google.com/a/macros/esm.co.jp/s/AKfycbxl8bQppTmCN2fRqyM6bwGr6649nwYkTCIyIA7TNBAEa9ixFac1WbhSWHxa8AtP8UU7AQ/exec

2022-09-05 23:18 UTC, hyamakawa commented
@k-shimada-esm lgtm🐁

2022-09-11 11:46 UTC, merged

2022-09-11 11:46 UTC, k-shimada-esm commented
LGTMをいただいたのでマージします。